### ISSUE TITLE
Asciidoc Required

### ISSUE THREAD

**Issue by Baldomo** [DelusionalLogic/bard#10]
As of now, bard **requires** Asciidoc to build documentation, however I believe it should be optional because Asciidoc will install a lot of its missing depedencies and in my case it would take up about 1.2 gb of storage. This is not really worth it nor strictly necessary for this kind of program.

Example output:
![cropped](https://cloud.githubusercontent.com/assets/17025402/26048851/5aaf946a-3948-11e7-8b91-312f4f9ba046.jpg)

**Comment by DelusionalLogic** [comment]
I don't think PKGBUILD supports optional makedepends. Am i wrong?

**Comment by Baldomo** [comment]
From what I understood [in the Arch wiki about PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD) the 'optdepends' array let's you add dependencies that are not strictly required to the build.

**Comment by DelusionalLogic** [comment]
I don't think optdepends is supposed to be for dependencies during build. Most AUR helpers don't support that. I'll look into making it optional in the configure script. Maybe i can make it a file variable in the PKGBUILD then.

Would that be acceptable?

**Comment by Baldomo** [comment]
Sounds fine by me :)

But what about ['makedepends'](https://wiki.archlinux.org/index.php/PKGBUILD#makedepends)? Also, which helpers do you think **are** gonna support this?

**Comment by DelusionalLogic** [comment]
Makedepends is what asciidoc already is listed as, which means it's marked no longer needed after build. Makedepends doesn't have any support for optional dependencies during build, at least to my knowledge.

**Comment by Baldomo** [comment]
Bummer. What is it that requires asciidoc to build? Isn't documentation and stuff optional, functionality-wise speaking?

**Comment by DelusionalLogic** [comment]
man pages are usually part of the default build, and that's what i use asciidoc to generate.

If you don't care about man pages it really don't serve and functional purpose, But it's a hard dependency in the automake configuration used to build the project currently.

**Comment by Baldomo** [comment]
Ok, I see. Will work my way around not to include asciidoc in the build. What should I modify apart from the configure and configure.ac scripts?

**Comment by DelusionalLogic** [comment]
So i updated the rewire branch, hopefully it works. You should be able to set ```WANT_DOC=no``` to disable documentation.

**Comment by Baldomo** [comment]
Lovely, thank you! Will test tomorrow (on multiple machines) and keep this issue updated.

**Comment by DelusionalLogic** [comment]
So, did you ever get it to work?

**Comment by Baldomo** [comment]
Sorry for keeping you waiting but my laptop broke and my Raspi Pi 3 doesn't boot for whatever reason. As soon as I have some spare time to fix everything, the first thing I'll do is build bard. I will close this issue if everything goes fine, don't worry.

**Comment by DelusionalLogic** [comment]
That's unfortunate, I hope you get it working again. Anyway, thanks for the update.
