### ISSUE TITLE
bard requires restart after changing multi-monitor settings.

### ISSUE THREAD

**Issue by VirtualSatai** [DelusionalLogic/bard#3]
Upon changing multi-monitor settings, bard requires a restart in order to work.

**Comment by DelusionalLogic** [comment]
Bard doesn't actually care about multi-monitor setups, all that is handled by lemonbar.

One possible solution would be to restart lemonbar when the monitor configuration is changed.

Another would be to get lemonbar to fix it, this would be preferred. They already have an issue filed: LemonBoy/bar#135

**Comment by DelusionalLogic** [comment]
Lemonboy/bar#135

**Comment by DelusionalLogic** [comment]
I've submitted a fix to the lemonbar maintainers, we'll see how it goes.

**Comment by VirtualSatai** [comment]
oh shiiit whaattuuuuuuuppppppppppp?

**Comment by DelusionalLogic** [comment]
So, the patch was rejected. I don't know where that leaves us.

I might implement it in the future.
