### ISSUE TITLE
Color in simple formatting

### ISSUE THREAD

**Issue by SevereOverfl0w** [DelusionalLogic/bard#6]
I couldn't figure out how to do colour in simple formatting, I tried your configs, but couldn't get them working. I think I might not have xrdb/Xresources setup correctly. Can you point me in the right direction?

```
[unit]
name=Clock
type=poll

[display]
command=date "+%a %b %d, %T"
format="%{F$color[red]} $1%{F-}"
interval=1
```

Results in:

```
%{F} Wed Sep 28, 12:49:39%{r}
```

How do I get it to pull out a colour correctly from the array?

**Comment by DelusionalLogic** [comment]
Looking at the dotfiles you have in your `.files` repo it does indeed look like you haven't defined the Xresources colors.

Personally I use colors from the base16 colorscheme, but I did at some point use the colors here: https://github.com/DelusionalLogic/dotfiles/blob/bspwm/Xorg/.config/xcolors/bold

To use them you just append the file to your existing .Xresources file.

Personally i like to keep it separated from my other xrdb definitions, so I have a separate folder and include them into the original .Xresources via `#include "<file>"`

**Comment by SevereOverfl0w** [comment]
I realised that I forgot to run `xrdb -merge` after updating my `.Xresources` locally. Oops!

Thanks for taking the time to reply.
